apiVersion: v2
type: application
name: redis
description: A Helm chart for Redis
version: 0.0.3
appVersion: "6.2.6"

home: https://github.com/pascaliske/helm-charts/tree/master/charts/redis
sources:
  - https://github.com/pascaliske/helm-charts
  - https://github.com/docker-library/redis
  - https://redis.io
keywords:
  - redis
maintainers:
  - name: pascaliske
    email: info@pascaliske.dev
    url: https://pascaliske.dev
